Algoritmo "Calc_cientifica"
// 
//  
// Descrição   : Calculadora cientifica  - BancodeBravos
// Autor(a)    : Matheus Volotao, Matheus Souza, Bruna Camille, Guilherme C.
// Abimael S., Eduardo D., Joao,Caue,Raissa J.,
// Data atual  : 9/14/2024

Var // DECLARACAO DAS FUNCOES/PROCEDIMENTOS AQUI
gv_retBaseDez:inteiro


funcao f_baseDezBaseDois(x:inteiro):inteiro

var
//declaracao loc baseDezBaseDois

fimfuncao


Inicio //INICIO DO PROGRAM PRINCIPAL





Fimalgoritmo
